
# HYDRA CONFIG

#defaults:
#   - defaults

args:
  config: null # "What configuration file to use to overwrite shared/defaults.yaml"
  base_dir: ""
  run_id: 1
  note: null # Note about this training for comet logging
  no_comet: False # DON'T use comet.ml to log experiment
  resume: False # Load latest ckpt
  tags: null
  dev: False # Run this script in development mode
  version_base: "1.1"